title = 'Chris Kendrick'
baseURL = "https://yellow-ground-0f3f3a910.2.azurestaticapps.net/"
languageCode = 'en-us'
theme = "ananke"

# SectionPagesMenu = "main"
SectionPagesMenu = ""
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Chris Kendrick Photography"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
[[menu.main]]
  name = 'Articles'
  url = '/post'
  weight = 20
[[menu.main]]
  name = 'Contact'
  url = '/page/contact'
  weight = 30
[[menu.main]]
  name = 'About'
  url = '/page/about'
  weight = 40
[[menu.main]]
  name = 'Categories'
  url = '/categories'
  weight = 80
[[menu.main]]
  name = 'Tags'
  url = '/tags'
  weight = 90


[params]
  text_color = ""
  author = ""
  favicon = "/images/ck-favicon.png"
  site_logo = "/images/CKP-logo.png"
  description = "Chris Kendrick Photography"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 6
  show_reading_time = true
  custom_css = ["_styles.css"]

  # Formspree
  # formspreeId = "mqknwqkw"

[[params.ananke_socials]]
  name = "facebook"
  url = "https://facebook.com/ChrisKendrickPhotographyLLC"
[[params.ananke_socials]]
  name = "instagram"
  url   = "https://www.instagram.com/chriskendrickphotography/"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = true
